apiversion: networking.k8s. io/v1beta1 
kind: Ingress 
metadata: 
      name: ingress-alb 
      labels: 
          app: ingress
      annotations: 
           kubernetes.io/ingress.class: "nginx" 
           alb.ingress.kubernetes.io/scheme: internet-facing 
           alb.ingress.kubernetes.io/backend-protocol:  HTTPS 
           alb.ingress.kubernetes.io/healthcheck-protocol:  HTTPS 
           alb.ingress.kubernetes.io/listen-ports: '[("HTTP": 80},HTTPS": 443)]' 
           alb.ingress.kubernetes.io/certificate-arn:  arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxx 
           alb.ingress.kubernetes.io/inbound-cidrs:  10.0.0.0/24
           alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-ReS-2019-08" 
           alb.ingress.kubernetes.io/successCodes: "200-404" 
           ingress.kubernetesdo/rewrite-target:  / 
           nginx.ingress.kubernetesdo/backend-protocol: HTTPS 
           nginx.org/ssl-services: plat,dp,online 
spec: 
    rules: 
    -   host: dp.amazonaws.com
        http: 
            paths: 
            -    backend: 
                      serviceName: desktop 
                      servicePort: 9999 
    -   host: online.amzonaws.domain 
        http: 
            paths: 
            -    backend: 
                      serviceName: online 
                      servicePort: 443 
    -   host: plat.amzonaws.domain 
        http: 
            paths: 
            -    backend: 
                      serviceName: plat 
                      serviceport: 9000 

