apiVersion: v1
kind: PersistentVolume
metadata:
      name: my-app-persistent
spec:
     storageClassName: plat-persistent
     accessModes:
         -    ReadWriteMany
     nfs:
         path:  "/"
         server: <<efs-ip-addr>>
         readOnly: false
     capacity:
        storage: 10Gi
