apiVersion: v1
kind: PersistentVolumeClaim
metadata:
      name:  my-app-claim
spec:
     storageClassName: plat-persistent
     accessModes:
          -   ReadWriteMany
     resources:
         requests:
              storage: 10Gi
